disabled invoking deckdebuild with --faketime
rational:
    - deckdebuild's faketime hack causes issues with dh_auto_configure
      when checking if build environment is sane:

        error: newly created file is older than distributed files!
        check your system clock

      additionally, it is not reliable enough in creating deterministic
      builds, the initial rational for adding support.

    - disabling for now, will re-enable when the above issues are fixed.